import amazon_logo from "./amazon.png"
import apple_logo from "./apple.png"
import discord_logo from "./discord.png"
import github_logo from "./github.png"
import google_logo from "./google.png"
import microsoft_logo from "./microsoft.png"
import twitter_logo from "./twitter.png"
import logo from "./logo.svg"
import sun from "./sun.png"
import search_svg from "./search.svg"
import arrow_svg from "./arrow.svg"
import edit_svg from "./edit.svg"
import add_svg from "./add.svg"
import delete_svg from "./delete.svg"
import check_svg from "./check.svg"
import sort_svg from "./sort.svg"
import star_svg from "./star.svg"
import marker_star_svg from "./marker_star.svg"
import avatar_svg from "./avatar.svg"
import enter_png from "./enter.png"
import link_svg from "./link.svg"
import tickbox_png from "./tickbox.png"
import plus_svg from "./plus_icon.svg"
import account_arrow_svg from "./account_arrow.svg"
import blank_page_svg from "./blank_page.svg"

export {
    blank_page_svg, account_arrow_svg, plus_svg, marker_star_svg, tickbox_png, link_svg, enter_png, avatar_svg, amazon_logo, apple_logo, discord_logo, github_logo, google_logo, microsoft_logo, twitter_logo, logo, sun, search_svg, arrow_svg, edit_svg, add_svg, delete_svg, check_svg, sort_svg, star_svg
}